[workspace]
members = [
    "_100_doors",
    "a_plus_b",
    "bitmap",
    "execute_brainxxxx",
    "lexical_analyzer",
    "syntax_analyzer",
    "ast_interpreter",
    "code_generator",
    "virtual_machine_interpreter",
]
